import React, { useState, useMemo, useEffect } from 'react';
import { Search, Filter, BookOpen, Layers, Clock, XCircle, PlayCircle, Loader2, AlertCircle, Database, Copy, Check, RefreshCw, ArrowUp, PanelLeftClose, PanelLeftOpen, X } from 'lucide-react';
import { CourseCategory, Course, FilterState } from './types';
import CourseCard from './components/CourseCard';
import CourseModal from './components/CourseModal';
import { fetchCoursesFromSupabase } from './services/courseDataService';
import { APP_VERSION } from './constants';

const SETUP_SQL = `create table courses (
  id bigint generated by default as identity primary key,
  course_category text,
  course_name text,
  source text,
  lecturer text,
  total_duration text,
  total_videos text,
  video_topic text,
  video_duration text,
  video_link text
);

alter table courses enable row level security;

create policy "Public courses are viewable by everyone."
  on courses for select
  using ( true );`;

// Definition of Duration Ranges
const DURATION_RANGES = [
  { key: '0-60', label: '< 1 hr', min: 0, max: 60 },
  { key: '60-120', label: '1 - 2 hrs', min: 60, max: 120 },
  { key: '120-180', label: '2 - 3 hrs', min: 120, max: 180 },
  { key: '180-300', label: '3 - 5 hrs', min: 180, max: 300 },
  { key: '300-600', label: '5 - 10 hrs', min: 300, max: 600 },
  { key: '600-plus', label: '> 10 hrs', min: 600, max: Infinity },
];

const App: React.FC = () => {
  const [courses, setCourses] = useState<Course[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [showScrollTop, setShowScrollTop] = useState(false);
  
  const [selectedCourse, setSelectedCourse] = useState<Course | null>(null);
  const [initialVideoIndex, setInitialVideoIndex] = useState<number | null>(null);
  const [showFiltersMobile, setShowFiltersMobile] = useState(false);
  const [isSidebarOpen, setIsSidebarOpen] = useState(false); // Default closed on desktop
  
  const [filters, setFilters] = useState<FilterState>({
    search: '',
    categories: [],
    sources: [],
    durationRange: null
  });

  // Version Check Logging
  useEffect(() => {
    console.log(`%c SkillZaty v${APP_VERSION} Running `, 'background: #4f46e5; color: white; font-weight: bold; padding: 4px 8px; border-radius: 4px;');
  }, []);

  // Auto-scroll to top when filters change
  useEffect(() => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }, [filters]);

  // Handle Scroll to Top Visibility
  // Since we removed overflow-y-auto from main, the window now scrolls
  useEffect(() => {
    const handleScroll = () => {
      setShowScrollTop(window.scrollY > 300);
    };
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  // Fetch Data on Mount
  useEffect(() => {
    const loadCourses = async () => {
      try {
        setLoading(true);
        const data = await fetchCoursesFromSupabase();
        setCourses(data);
        // Sidebar is kept closed by default (removed auto-open logic)
      } catch (err: any) {
        console.error("App load error:", err);
        const msg = err.message || '';
        
        if (msg === 'TABLE_NOT_FOUND' || msg.includes('Could not find the table') || msg.includes('relation') || msg.includes('does not exist')) {
          setError('TABLE_NOT_FOUND');
        } else if (msg === 'SUPABASE_NOT_CONFIGURED') {
          setError('Supabase is not configured.');
        } else {
          setError(msg || 'Failed to load courses.');
        }
      } finally {
        setLoading(false);
      }
    };

    loadCourses();
  }, []);

  const copySQL = () => {
    navigator.clipboard.writeText(SETUP_SQL);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Derived Available Options for Sidebar
  const availableCategories = useMemo(() => {
    const cats = new Set<string>();
    courses.forEach(c => cats.add(c.category));
    return Array.from(cats).sort();
  }, [courses]);

  const availableSources = useMemo(() => {
    const srcs = new Set<string>();
    courses.forEach(c => srcs.add(c.source));
    return Array.from(srcs).sort();
  }, [courses]);

  // Derived Filtered List
  const filteredCourses = useMemo(() => {
    return courses.filter(course => {
      const searchLower = filters.search.toLowerCase();
      
      // Search: Name, Lecturer, Course Topics, OR Video Titles
      const matchesSearch = 
        course.name.toLowerCase().includes(searchLower) ||
        course.lecturer.toLowerCase().includes(searchLower) ||
        course.topics.some(t => t.toLowerCase().includes(searchLower)) ||
        course.videos.some(v => v.title.toLowerCase().includes(searchLower));

      // Category
      const matchesCategory = 
        filters.categories.length === 0 || 
        filters.categories.includes(course.category);

      // Source
      const matchesSource = 
        filters.sources.length === 0 || 
        filters.sources.includes(course.source);

      // Duration
      let matchesDuration = true;
      if (filters.durationRange) {
        const range = DURATION_RANGES.find(r => r.key === filters.durationRange);
        if (range) {
          matchesDuration = course.durationMinutes >= range.min && course.durationMinutes < range.max;
        }
      }

      return matchesSearch && matchesCategory && matchesSource && matchesDuration;
    });
  }, [filters, courses]);

  const totalMatchingVideos = useMemo(() => {
    if (!filters.search) return 0;
    const searchLower = filters.search.toLowerCase();
    return filteredCourses.reduce((acc, course) => {
      return acc + course.videos.filter(v => v.title.toLowerCase().includes(searchLower)).length;
    }, 0);
  }, [filteredCourses, filters.search]);

  // Handlers
  const handleCourseClick = (course: Course, videoIndex?: number) => {
    setSelectedCourse(course);
    setInitialVideoIndex(videoIndex ?? null);
  };

  const toggleCategory = (cat: string) => {
    setFilters(prev => ({
      ...prev,
      categories: prev.categories.includes(cat)
        ? prev.categories.filter(c => c !== cat)
        : [...prev.categories, cat]
    }));
  };

  const toggleSource = (source: string) => {
    setFilters(prev => ({
      ...prev,
      sources: prev.sources.includes(source)
        ? prev.sources.filter(s => s !== source)
        : [...prev.sources, source]
    }));
  };

  const resetFilters = () => {
    setFilters({
      search: '',
      categories: [],
      sources: [],
      durationRange: null
    });
  };

  const clearSearch = () => {
    setFilters(prev => ({ ...prev, search: '' }));
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-50 flex flex-col items-center justify-center text-slate-500 font-inter">
        <Loader2 size={48} className="animate-spin text-indigo-600 mb-4" />
        <h2 className="text-lg font-semibold text-slate-700">Loading SkillZaty Database...</h2>
        <p className="text-sm">Fetching courses from Supabase</p>
      </div>
    );
  }

  if (error) {
    const isTableError = error === 'TABLE_NOT_FOUND';
    return (
      <div className="min-h-screen bg-slate-50 flex flex-col items-center justify-center text-slate-500 p-4 font-inter">
        <AlertCircle size={48} className="text-red-500 mb-4" />
        <h2 className="text-lg font-semibold text-slate-800">Connection Error</h2>
        <p className="text-sm max-w-md text-center mb-6 text-slate-600">
          {isTableError ? "We couldn't find the 'courses' table in your database." : error}
        </p>

        {isTableError && (
          <div className="bg-white p-6 rounded-lg shadow-sm border border-slate-200 max-w-2xl w-full text-left mb-6">
            <h3 className="font-bold text-slate-900 mb-3 flex items-center">
              <Database size={16} className="mr-2 text-indigo-600" /> 
              One-Click Database Setup
            </h3>
            <p className="text-sm text-slate-600 mb-4">
              To fix this, go to your <strong>Supabase Dashboard</strong>, open the <strong>SQL Editor</strong>, and run the following script:
            </p>
            
            <div className="relative">
              <pre className="bg-slate-900 text-slate-300 p-4 rounded-lg text-xs overflow-x-auto font-mono leading-relaxed border border-slate-700">
                {SETUP_SQL}
              </pre>
              <button 
                onClick={copySQL}
                className="absolute top-2 right-2 bg-slate-700 hover:bg-slate-600 text-white px-3 py-1.5 rounded text-xs font-medium flex items-center transition-colors"
              >
                {copied ? <Check size={14} className="mr-1.5 text-green-400" /> : <Copy size={14} className="mr-1.5" />}
                {copied ? 'Copied!' : 'Copy SQL'}
              </button>
            </div>
            
            <div className="mt-4 flex items-start gap-2 text-xs text-amber-700 bg-amber-50 p-3 rounded border border-amber-100">
              <AlertCircle size={16} className="shrink-0 mt-0.5" />
              <div>
                <p className="font-semibold mb-1">Important:</p>
                <p>1. Run the SQL above in Supabase.</p>
                <p>2. Insert your course data into the <strong>courses</strong> table.</p>
                <p>3. <strong>Refresh this page</strong> to see your data.</p>
              </div>
            </div>
          </div>
        )}

        <button 
          onClick={() => window.location.reload()}
          className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors shadow-sm font-medium"
        >
          <RefreshCw size={16} />
          Reload Application
        </button>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 font-inter flex flex-col relative">
      
      {/* Navbar */}
      <header className="sticky top-0 z-40 bg-white border-b border-slate-200 shadow-[0_1px_3px_rgba(0,0,0,0.05)] h-16">
        <div className="w-full px-4 sm:px-6 lg:px-8 h-full flex items-center justify-between">
          <div className="flex items-center gap-4">
            {/* Desktop Sidebar Toggle */}
            <button 
              onClick={() => setIsSidebarOpen(!isSidebarOpen)}
              className="hidden md:flex p-2 text-slate-500 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors"
              title={isSidebarOpen ? "Collapse Sidebar" : "Expand Sidebar"}
            >
              {isSidebarOpen ? <PanelLeftClose size={20} /> : <PanelLeftOpen size={20} />}
            </button>

            <div className="flex items-center space-x-2">
              <div className="bg-gradient-to-br from-indigo-600 to-violet-700 p-1.5 rounded-lg shadow-sm">
                <Layers className="text-white" size={20} />
              </div>
              <h1 className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-indigo-700 to-violet-700 tracking-tight">
                SkillZaty
              </h1>
            </div>
          </div>
          
          <div className="hidden md:flex items-center flex-1 max-w-2xl mx-8">
            <div className="relative w-full group">
              <div className="absolute inset-y-0 left-0 pl-3.5 flex items-center pointer-events-none">
                <Search className="h-4 w-4 text-slate-400 group-focus-within:text-indigo-500 transition-colors" />
              </div>
              <input
                type="text"
                className="block w-full pl-10 pr-10 py-2.5 border border-slate-200 rounded-xl leading-5 bg-slate-50 placeholder-slate-400 focus:outline-none focus:bg-white focus:ring-2 focus:ring-indigo-100 focus:border-indigo-400 transition-all text-sm font-medium text-slate-700"
                placeholder="Search courses, video topics, or lecturers..."
                value={filters.search}
                onChange={(e) => setFilters(prev => ({...prev, search: e.target.value}))}
              />
              {filters.search && (
                <button 
                  onClick={clearSearch}
                  className="absolute inset-y-0 right-0 pr-3 flex items-center text-slate-400 hover:text-slate-600 transition-colors"
                >
                  <X size={16} />
                </button>
              )}
            </div>
          </div>

          <div className="flex items-center gap-2 sm:gap-3">
             <button 
                className="md:hidden p-2 text-slate-500 hover:text-indigo-600 hover:bg-slate-100 rounded-lg"
                onClick={() => setShowFiltersMobile(!showFiltersMobile)}
             >
               <Filter size={24} />
             </button>
             {/* Mobile Course Count - Now Visible */}
             <div className="flex items-center text-xs font-semibold bg-indigo-50 px-2 sm:px-3 py-1.5 rounded-full border border-indigo-100 text-indigo-700 whitespace-nowrap">
                <span className="mr-1">{filteredCourses.length}</span> <span className="hidden sm:inline">Courses</span><span className="sm:hidden">Crse</span>
                {filters.search && totalMatchingVideos > 0 && (
                   <>
                     <span className="mx-1 sm:mx-2 text-indigo-300">|</span>
                     <span className="flex items-center">
                       <PlayCircle size={12} className="mr-1 hidden sm:block" />
                       {totalMatchingVideos} <span className="hidden sm:inline ml-1">Vids</span>
                     </span>
                   </>
                )}
             </div>
          </div>
        </div>
        
        {/* Mobile Search - Visible only on small screens */}
        <div className="md:hidden px-4 pb-4 border-t border-slate-100 pt-3">
             <div className="relative w-full">
              <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <Search className="h-4 w-4 text-slate-400" />
              </div>
              <input
                type="text"
                className="block w-full pl-10 pr-10 py-2 border border-slate-200 rounded-lg bg-slate-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 sm:text-sm"
                placeholder="Search..."
                value={filters.search}
                onChange={(e) => setFilters(prev => ({...prev, search: e.target.value}))}
              />
              {filters.search && (
                <button 
                  onClick={clearSearch}
                  className="absolute inset-y-0 right-0 pr-3 flex items-center text-slate-400 hover:text-slate-600 transition-colors"
                >
                  <X size={16} />
                </button>
              )}
            </div>
        </div>
      </header>

      {/* Sidebar Filters - Fixed Overlay */}
      <aside 
          className={`
              fixed top-16 bottom-0 left-0 z-30 w-72 bg-white border-r border-slate-200 shadow-2xl transform transition-transform duration-300 ease-in-out
              ${showFiltersMobile ? 'translate-x-0' : '-translate-x-full'}
              md:${isSidebarOpen ? 'translate-x-0' : '-translate-x-full'}
          `}
          style={{ height: 'calc(100vh - 64px)' }} // Ensure it doesn't go behind navbar
      >
        <div className="h-full overflow-y-auto p-5 pb-24 no-scrollbar">
          
          {/* Mobile Header */}
          <div className="flex justify-between items-center md:hidden mb-6">
              <h2 className="font-bold text-lg text-slate-900">Filters</h2>
              <button 
              onClick={() => setShowFiltersMobile(false)}
              className="p-1 text-slate-400 hover:text-slate-600"
              >
              <XCircle size={24} />
              </button>
          </div>

          {/* Desktop Filter Header (Only when open) */}
          <div className="hidden md:flex justify-between items-center mb-6">
              <h2 className="font-bold text-sm text-slate-500 uppercase tracking-wider">Refine Results</h2>
              {(filters.categories.length > 0 || filters.sources.length > 0 || filters.durationRange !== null) && (
                <button 
                  onClick={resetFilters}
                  className="text-[10px] text-indigo-600 font-bold hover:underline"
                >
                  RESET
                </button>
              )}
          </div>

          <div className="space-y-8">
              {/* Categories */}
              {availableCategories.length > 0 && (
              <div>
                  <h3 className="text-sm font-bold text-slate-900 mb-3 flex items-center">
                    <BookOpen size={16} className="mr-2 text-indigo-500" /> Category
                  </h3>
                  <div className="space-y-2.5">
                  {availableCategories.map(cat => (
                      <label key={cat} className="flex items-center space-x-3 cursor-pointer group select-none">
                      <div className={`w-4 h-4 rounded border flex items-center justify-center transition-all flex-shrink-0 ${filters.categories.includes(cat) ? 'bg-indigo-600 border-indigo-600 shadow-sm' : 'border-slate-300 bg-white group-hover:border-indigo-400'}`}>
                          {filters.categories.includes(cat) && <Check size={10} className="text-white" />}
                      </div>
                      <input 
                          type="checkbox" 
                          className="hidden"
                          checked={filters.categories.includes(cat)} 
                          onChange={() => toggleCategory(cat)}
                      />
                      <span className={`text-sm ${filters.categories.includes(cat) ? 'text-indigo-700 font-semibold' : 'text-slate-600 group-hover:text-slate-900'}`}>{cat}</span>
                      </label>
                  ))}
                  </div>
              </div>
              )}

              {/* Source */}
              {availableSources.length > 0 && (
              <div>
                  <h3 className="text-sm font-bold text-slate-900 mb-3 flex items-center">
                    <Layers size={16} className="mr-2 text-indigo-500" /> Platform
                  </h3>
                  <div className="space-y-2.5">
                  {availableSources.map(source => (
                      <label key={source} className="flex items-center space-x-3 cursor-pointer group select-none">
                      <div className={`w-4 h-4 rounded border flex items-center justify-center transition-all flex-shrink-0 ${filters.sources.includes(source) ? 'bg-indigo-600 border-indigo-600 shadow-sm' : 'border-slate-300 bg-white group-hover:border-indigo-400'}`}>
                          {filters.sources.includes(source) && <Check size={10} className="text-white" />}
                      </div>
                      <input 
                          type="checkbox" 
                          className="hidden"
                          checked={filters.sources.includes(source)} 
                          onChange={() => toggleSource(source)}
                      />
                      <span className={`text-sm ${filters.sources.includes(source) ? 'text-indigo-700 font-semibold' : 'text-slate-600 group-hover:text-slate-900'}`}>{source}</span>
                      </label>
                  ))}
                  </div>
              </div>
              )}

              {/* Duration */}
              <div>
                  <h3 className="text-sm font-bold text-slate-900 mb-3 flex items-center">
                    <Clock size={16} className="mr-2 text-indigo-500" /> Duration
                  </h3>
                  <div className="flex flex-col gap-2">
                  {DURATION_RANGES.map(range => (
                      <button 
                      key={range.key}
                      onClick={() => setFilters(prev => ({...prev, durationRange: prev.durationRange === range.key ? null : range.key}))}
                      className={`px-3 py-2 rounded-lg text-sm text-left transition-all border ${filters.durationRange === range.key ? 'bg-indigo-50 border-indigo-200 text-indigo-700 font-bold shadow-sm' : 'bg-white border-slate-200 text-slate-600 hover:border-indigo-300 hover:bg-slate-50'}`}
                      >
                        <div className="flex justify-between items-center">
                          {range.label}
                          {filters.durationRange === range.key && <Check size={14} />}
                        </div>
                      </button>
                  ))}
                  </div>
              </div>

              {/* Mobile Reset */}
              <div className="md:hidden pt-4 border-t border-slate-100">
                <button 
                  onClick={resetFilters}
                  className="w-full py-2 text-center text-sm text-red-500 font-medium border border-red-200 rounded-lg hover:bg-red-50"
                >
                  Clear All Filters
                </button>
              </div>
          </div>
        </div>
      </aside>

      {/* Overlay for mobile sidebar */}
      {showFiltersMobile && (
        <div 
          className="fixed inset-0 z-20 bg-slate-900/50 backdrop-blur-sm md:hidden"
          onClick={() => setShowFiltersMobile(false)}
        />
      )}

      {/* Main Content Area */}
      <main className="w-full pb-20"> 
        <div className="max-w-[1600px] mx-auto px-4 sm:px-6 lg:px-8 py-8 w-full">
          
          {/* Active Filters Display */}
          {(filters.categories.length > 0 || filters.sources.length > 0 || filters.durationRange) && (
            <div className="mb-6 flex flex-wrap gap-2 items-center">
                <span className="text-xs font-semibold text-slate-400 mr-2 uppercase tracking-wide">Active Filters:</span>
                {filters.categories.map(c => (
                  <button key={c} onClick={() => toggleCategory(c)} className="flex items-center gap-1 px-3 py-1 bg-white border border-slate-200 rounded-full text-xs font-medium text-indigo-600 hover:bg-red-50 hover:text-red-500 hover:border-red-200 transition-colors shadow-sm">
                    {c} <X size={12} />
                  </button>
                ))}
                {filters.sources.map(s => (
                  <button key={s} onClick={() => toggleSource(s)} className="flex items-center gap-1 px-3 py-1 bg-white border border-slate-200 rounded-full text-xs font-medium text-blue-600 hover:bg-red-50 hover:text-red-500 hover:border-red-200 transition-colors shadow-sm">
                    {s} <X size={12} />
                  </button>
                ))}
                {filters.durationRange && (
                  <button onClick={() => setFilters(prev => ({...prev, durationRange: null}))} className="flex items-center gap-1 px-3 py-1 bg-white border border-slate-200 rounded-full text-xs font-medium text-emerald-600 hover:bg-red-50 hover:text-red-500 hover:border-red-200 transition-colors shadow-sm">
                    {DURATION_RANGES.find(r => r.key === filters.durationRange)?.label} <X size={12} />
                  </button>
                )}
                <button onClick={resetFilters} className="text-xs text-slate-500 hover:text-red-600 underline ml-2">Clear all</button>
            </div>
          )}

          {filteredCourses.length > 0 ? (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
              {filteredCourses.map(course => (
                <CourseCard 
                  key={course.id} 
                  course={course} 
                  searchQuery={filters.search}
                  onClick={handleCourseClick} 
                />
              ))}
            </div>
          ) : (
            <div className="flex flex-col items-center justify-center py-24 text-slate-400">
              <div className="bg-white p-6 rounded-full shadow-sm mb-4">
                <Search size={40} className="text-indigo-200" />
              </div>
              <h3 className="text-lg font-bold text-slate-700 mb-2">No courses found</h3>
              <p className="text-sm text-slate-500 max-w-xs text-center">We couldn't find any courses matching your specific criteria.</p>
              <button 
                onClick={resetFilters}
                className="mt-6 px-6 py-2 bg-indigo-600 text-white text-sm font-medium rounded-lg hover:bg-indigo-700 transition-colors shadow-sm"
              >
                Clear all filters
              </button>
            </div>
          )}
        </div>
      </main>

      {/* Scroll to Top Button */}
      {showScrollTop && (
        <button
          onClick={scrollToTop}
          className="fixed bottom-20 right-6 z-30 bg-white text-slate-600 p-3 rounded-full shadow-lg border border-slate-200 hover:bg-indigo-600 hover:text-white transition-all duration-300 transform hover:scale-110 group"
          aria-label="Scroll to top"
        >
          <ArrowUp size={20} className="group-hover:-translate-y-1 transition-transform" />
        </button>
      )}

      {/* Fixed Footer */}
      <footer className="fixed bottom-0 left-0 right-0 bg-white border-t border-slate-200 py-4 z-40">
        <div className="w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex items-center justify-between text-xs text-slate-500">
           <div className="flex items-center gap-2">
             <div className="bg-slate-100 p-1 rounded">
               <Layers size={12} className="text-indigo-600" />
             </div>
             <span className="font-semibold text-slate-700">SkillZaty</span>
             <span>© 2025</span>
           </div>
           <p className="font-mono text-[10px] text-slate-400 bg-slate-50 px-2 py-1 rounded">v{APP_VERSION}</p>
        </div>
      </footer>

      <CourseModal 
        course={selectedCourse} 
        initialVideoIndex={initialVideoIndex}
        onClose={() => {
          setSelectedCourse(null);
          setInitialVideoIndex(null);
        }} 
      />
      
    </div>
  );
};

export default App;