import React, { useState, useMemo, useEffect } from 'react';
import { Search, Filter, BookOpen, Layers, Clock, XCircle, PlayCircle, Loader2, AlertCircle, Database, Copy, Check, RefreshCw, ArrowUp } from 'lucide-react';
import { CourseCategory, Course, FilterState } from './types';
import CourseCard from './components/CourseCard';
import CourseModal from './components/CourseModal';
import { fetchCoursesFromSupabase } from './services/courseDataService';
import { APP_VERSION } from './constants';

const SETUP_SQL = `create table courses (
  id bigint generated by default as identity primary key,
  course_category text,
  course_name text,
  source text,
  lecturer text,
  total_duration text,
  total_videos text,
  video_topic text,
  video_duration text,
  video_link text
);

alter table courses enable row level security;

create policy "Public courses are viewable by everyone."
  on courses for select
  using ( true );`;

const App: React.FC = () => {
  const [courses, setCourses] = useState<Course[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [showScrollTop, setShowScrollTop] = useState(false);
  
  const [selectedCourse, setSelectedCourse] = useState<Course | null>(null);
  const [initialVideoIndex, setInitialVideoIndex] = useState<number | null>(null);
  const [showFiltersMobile, setShowFiltersMobile] = useState(false);
  
  const [filters, setFilters] = useState<FilterState>({
    search: '',
    categories: [],
    sources: [],
    maxDuration: null
  });

  // Version Check Logging
  useEffect(() => {
    console.log(`%c SkillZaty v${APP_VERSION} Running `, 'background: #4f46e5; color: white; font-weight: bold; padding: 4px 8px; border-radius: 4px;');
  }, []);

  // Handle Scroll to Top Visibility
  useEffect(() => {
    const handleScroll = () => {
      setShowScrollTop(window.scrollY > 300);
    };
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  // Fetch Data on Mount
  useEffect(() => {
    const loadCourses = async () => {
      try {
        setLoading(true);
        const data = await fetchCoursesFromSupabase();
        setCourses(data);
      } catch (err: any) {
        console.error("App load error:", err);
        // Handle specific error messages from service
        const msg = err.message || '';
        
        if (msg === 'TABLE_NOT_FOUND' || msg.includes('Could not find the table') || msg.includes('relation') || msg.includes('does not exist')) {
          setError('TABLE_NOT_FOUND');
        } else if (msg === 'SUPABASE_NOT_CONFIGURED') {
          setError('Supabase is not configured.');
        } else {
          setError(msg || 'Failed to load courses.');
        }
      } finally {
        setLoading(false);
      }
    };

    loadCourses();
  }, []);

  const copySQL = () => {
    navigator.clipboard.writeText(SETUP_SQL);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Derived Available Options for Sidebar
  const availableCategories = useMemo(() => {
    const cats = new Set<string>();
    courses.forEach(c => cats.add(c.category));
    return Array.from(cats).sort();
  }, [courses]);

  const availableSources = useMemo(() => {
    const srcs = new Set<string>();
    courses.forEach(c => srcs.add(c.source));
    return Array.from(srcs).sort();
  }, [courses]);

  const availableDurationOptions = useMemo(() => {
    return {
      hasShort: courses.some(c => c.durationMinutes < 300), // < 5h
      hasMedium: courses.some(c => c.durationMinutes >= 300 && c.durationMinutes <= 1200), // 5-20h
      hasLong: courses.some(c => c.durationMinutes > 1200) // > 20h
    };
  }, [courses]);

  // Derived Filtered List
  const filteredCourses = useMemo(() => {
    return courses.filter(course => {
      const searchLower = filters.search.toLowerCase();
      
      // Search: Name, Lecturer, Course Topics, OR Video Titles
      const matchesSearch = 
        course.name.toLowerCase().includes(searchLower) ||
        course.lecturer.toLowerCase().includes(searchLower) ||
        course.topics.some(t => t.toLowerCase().includes(searchLower)) ||
        course.videos.some(v => v.title.toLowerCase().includes(searchLower));

      // Category
      const matchesCategory = 
        filters.categories.length === 0 || 
        filters.categories.includes(course.category);

      // Source
      const matchesSource = 
        filters.sources.length === 0 || 
        filters.sources.includes(course.source);

      // Duration
      let matchesDuration = true;
      if (filters.maxDuration !== null) {
        if (filters.maxDuration === 1) matchesDuration = course.durationMinutes < 300; // < 5h
        else if (filters.maxDuration === 2) matchesDuration = course.durationMinutes >= 300 && course.durationMinutes <= 1200;
        else if (filters.maxDuration === 3) matchesDuration = course.durationMinutes > 1200;
      }

      return matchesSearch && matchesCategory && matchesSource && matchesDuration;
    });
  }, [filters, courses]);

  const totalMatchingVideos = useMemo(() => {
    if (!filters.search) return 0;
    const searchLower = filters.search.toLowerCase();
    return filteredCourses.reduce((acc, course) => {
      return acc + course.videos.filter(v => v.title.toLowerCase().includes(searchLower)).length;
    }, 0);
  }, [filteredCourses, filters.search]);

  // Handlers
  const handleCourseClick = (course: Course, videoIndex?: number) => {
    setSelectedCourse(course);
    setInitialVideoIndex(videoIndex ?? null);
  };

  const toggleCategory = (cat: string) => {
    setFilters(prev => ({
      ...prev,
      categories: prev.categories.includes(cat)
        ? prev.categories.filter(c => c !== cat)
        : [...prev.categories, cat]
    }));
  };

  const toggleSource = (source: string) => {
    setFilters(prev => ({
      ...prev,
      sources: prev.sources.includes(source)
        ? prev.sources.filter(s => s !== source)
        : [...prev.sources, source]
    }));
  };

  const resetFilters = () => {
    setFilters({
      search: '',
      categories: [],
      sources: [],
      maxDuration: null
    });
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-50 flex flex-col items-center justify-center text-slate-500">
        <Loader2 size={48} className="animate-spin text-indigo-600 mb-4" />
        <h2 className="text-lg font-semibold text-slate-700">Loading SkillZaty Database...</h2>
        <p className="text-sm">Fetching courses from Supabase</p>
      </div>
    );
  }

  if (error) {
    const isTableError = error === 'TABLE_NOT_FOUND';
    return (
      <div className="min-h-screen bg-slate-50 flex flex-col items-center justify-center text-slate-500 p-4">
        <AlertCircle size={48} className="text-red-500 mb-4" />
        <h2 className="text-lg font-semibold text-slate-800">Connection Error</h2>
        <p className="text-sm max-w-md text-center mb-6 text-slate-600">
          {isTableError ? "We couldn't find the 'courses' table in your database." : error}
        </p>

        {isTableError && (
          <div className="bg-white p-6 rounded-lg shadow-sm border border-slate-200 max-w-2xl w-full text-left mb-6">
            <h3 className="font-bold text-slate-900 mb-3 flex items-center">
              <Database size={16} className="mr-2 text-indigo-600" /> 
              One-Click Database Setup
            </h3>
            <p className="text-sm text-slate-600 mb-4">
              To fix this, go to your <strong>Supabase Dashboard</strong>, open the <strong>SQL Editor</strong>, and run the following script:
            </p>
            
            <div className="relative">
              <pre className="bg-slate-900 text-slate-300 p-4 rounded-lg text-xs overflow-x-auto font-mono leading-relaxed border border-slate-700">
                {SETUP_SQL}
              </pre>
              <button 
                onClick={copySQL}
                className="absolute top-2 right-2 bg-slate-700 hover:bg-slate-600 text-white px-3 py-1.5 rounded text-xs font-medium flex items-center transition-colors"
              >
                {copied ? <Check size={14} className="mr-1.5 text-green-400" /> : <Copy size={14} className="mr-1.5" />}
                {copied ? 'Copied!' : 'Copy SQL'}
              </button>
            </div>
            
            <div className="mt-4 flex items-start gap-2 text-xs text-amber-700 bg-amber-50 p-3 rounded border border-amber-100">
              <AlertCircle size={16} className="shrink-0 mt-0.5" />
              <div>
                <p className="font-semibold mb-1">Important:</p>
                <p>1. Run the SQL above in Supabase.</p>
                <p>2. Insert your course data into the <strong>courses</strong> table.</p>
                <p>3. <strong>Refresh this page</strong> to see your data.</p>
              </div>
            </div>
          </div>
        )}

        <button 
          onClick={() => window.location.reload()}
          className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors shadow-sm font-medium"
        >
          <RefreshCw size={16} />
          Reload Application
        </button>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 font-inter flex flex-col relative">
      
      {/* Navbar */}
      <header className="sticky top-0 z-30 bg-white border-b border-slate-200 shadow-sm flex-none">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <div className="bg-indigo-600 p-1.5 rounded-lg">
              <Layers className="text-white" size={24} />
            </div>
            <h1 className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-indigo-600 to-violet-600">
              SkillZaty
            </h1>
          </div>
          
          <div className="hidden md:flex items-center flex-1 max-w-lg mx-8">
            <div className="relative w-full group">
              <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <Search className="h-4 w-4 text-slate-400 group-focus-within:text-indigo-500 transition-colors" />
              </div>
              <input
                type="text"
                className="block w-full pl-10 pr-3 py-2 border border-slate-200 rounded-lg leading-5 bg-slate-50 placeholder-slate-400 focus:outline-none focus:bg-white focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 transition-all sm:text-sm"
                placeholder="Search courses, video topics..."
                value={filters.search}
                onChange={(e) => setFilters(prev => ({...prev, search: e.target.value}))}
              />
            </div>
          </div>

          <div className="flex items-center">
             <button 
                className="md:hidden p-2 text-slate-500 hover:text-indigo-600"
                onClick={() => setShowFiltersMobile(!showFiltersMobile)}
             >
               <Filter size={24} />
             </button>
             <div className="hidden md:flex items-center text-xs font-medium bg-slate-100 px-3 py-1.5 rounded-full border border-slate-200">
                <span className="text-slate-600">{filteredCourses.length} Courses Found</span>
                {filters.search && totalMatchingVideos > 0 && (
                   <>
                     <span className="mx-2 text-slate-300">|</span>
                     <span className="text-indigo-600 flex items-center">
                       <PlayCircle size={12} className="mr-1" />
                       {totalMatchingVideos} Matching Videos
                     </span>
                   </>
                )}
             </div>
          </div>
        </div>
        
        {/* Mobile Search - Visible only on small screens */}
        <div className="md:hidden px-4 pb-4">
             <div className="relative w-full">
              <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <Search className="h-4 w-4 text-slate-400" />
              </div>
              <input
                type="text"
                className="block w-full pl-10 pr-3 py-2 border border-slate-200 rounded-lg bg-slate-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 sm:text-sm"
                placeholder="Search..."
                value={filters.search}
                onChange={(e) => setFilters(prev => ({...prev, search: e.target.value}))}
              />
            </div>
            {/* Mobile Stats */}
            {filters.search && totalMatchingVideos > 0 && (
              <div className="mt-2 text-xs text-indigo-600 font-medium flex items-center justify-end">
                 <PlayCircle size={12} className="mr-1" />
                 {totalMatchingVideos} matching videos found across {filteredCourses.length} courses
              </div>
            )}
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 flex-1 w-full pb-24">
        <div className="flex flex-col md:flex-row gap-8">
          
          {/* Sidebar Filters */}
          <aside className={`md:w-64 flex-shrink-0 ${showFiltersMobile ? 'block' : 'hidden md:block'}`}>
            <div className="sticky top-24 space-y-8">
              
              {/* Reset Button (Mobile) */}
              <div className="flex justify-between items-center md:hidden mb-4">
                <h2 className="font-bold text-lg">Filters</h2>
                <button 
                   onClick={resetFilters}
                   className="text-xs text-indigo-600 font-semibold"
                >
                  Reset All
                </button>
              </div>

              {/* Categories */}
              {availableCategories.length > 0 && (
                <div>
                  <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider mb-3 flex items-center">
                    <BookOpen size={14} className="mr-2 text-indigo-500" /> Category
                  </h3>
                  <div className="space-y-2">
                    {availableCategories.map(cat => (
                      <label key={cat} className="flex items-center space-x-2 cursor-pointer group">
                        <div className={`w-4 h-4 rounded border flex items-center justify-center transition-colors ${filters.categories.includes(cat) ? 'bg-indigo-600 border-indigo-600' : 'border-slate-300 bg-white group-hover:border-indigo-400'}`}>
                          {filters.categories.includes(cat) && <span className="text-white text-xs">✓</span>}
                        </div>
                        <input 
                          type="checkbox" 
                          className="hidden"
                          checked={filters.categories.includes(cat)} 
                          onChange={() => toggleCategory(cat)}
                        />
                        <span className={`text-sm ${filters.categories.includes(cat) ? 'text-indigo-700 font-medium' : 'text-slate-600 group-hover:text-slate-900'}`}>{cat}</span>
                      </label>
                    ))}
                  </div>
                </div>
              )}

              {/* Source */}
              {availableSources.length > 0 && (
                <div>
                  <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider mb-3 flex items-center">
                    <Layers size={14} className="mr-2 text-indigo-500" /> Platform
                  </h3>
                  <div className="space-y-2">
                    {availableSources.map(source => (
                      <label key={source} className="flex items-center space-x-2 cursor-pointer group">
                        <div className={`w-4 h-4 rounded border flex items-center justify-center transition-colors ${filters.sources.includes(source) ? 'bg-indigo-600 border-indigo-600' : 'border-slate-300 bg-white group-hover:border-indigo-400'}`}>
                          {filters.sources.includes(source) && <span className="text-white text-xs">✓</span>}
                        </div>
                        <input 
                          type="checkbox" 
                          className="hidden"
                          checked={filters.sources.includes(source)} 
                          onChange={() => toggleSource(source)}
                        />
                        <span className={`text-sm ${filters.sources.includes(source) ? 'text-indigo-700 font-medium' : 'text-slate-600 group-hover:text-slate-900'}`}>{source}</span>
                      </label>
                    ))}
                  </div>
                </div>
              )}

               {/* Duration */}
               {(availableDurationOptions.hasShort || availableDurationOptions.hasMedium || availableDurationOptions.hasLong) && (
                 <div>
                  <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider mb-3 flex items-center">
                    <Clock size={14} className="mr-2 text-indigo-500" /> Duration
                  </h3>
                  <div className="flex flex-col gap-2">
                    {availableDurationOptions.hasShort && (
                      <button 
                        onClick={() => setFilters(prev => ({...prev, maxDuration: prev.maxDuration === 1 ? null : 1}))}
                        className={`px-3 py-2 rounded-lg text-sm text-left transition-colors border ${filters.maxDuration === 1 ? 'bg-indigo-50 border-indigo-200 text-indigo-700 font-medium' : 'bg-white border-slate-200 text-slate-600 hover:border-indigo-300'}`}
                      >
                        Short (&lt; 5h)
                      </button>
                    )}
                    {availableDurationOptions.hasMedium && (
                      <button 
                        onClick={() => setFilters(prev => ({...prev, maxDuration: prev.maxDuration === 2 ? null : 2}))}
                        className={`px-3 py-2 rounded-lg text-sm text-left transition-colors border ${filters.maxDuration === 2 ? 'bg-indigo-50 border-indigo-200 text-indigo-700 font-medium' : 'bg-white border-slate-200 text-slate-600 hover:border-indigo-300'}`}
                      >
                        Medium (5h - 20h)
                      </button>
                    )}
                    {availableDurationOptions.hasLong && (
                      <button 
                        onClick={() => setFilters(prev => ({...prev, maxDuration: prev.maxDuration === 3 ? null : 3}))}
                        className={`px-3 py-2 rounded-lg text-sm text-left transition-colors border ${filters.maxDuration === 3 ? 'bg-indigo-50 border-indigo-200 text-indigo-700 font-medium' : 'bg-white border-slate-200 text-slate-600 hover:border-indigo-300'}`}
                      >
                        Long (&gt; 20h)
                      </button>
                    )}
                  </div>
                </div>
              )}

              {/* Clear Filters Button (Desktop) */}
              {(filters.categories.length > 0 || filters.sources.length > 0 || filters.maxDuration !== null || filters.search) && (
                <button 
                  onClick={resetFilters}
                  className="hidden md:flex items-center text-sm text-red-500 hover:text-red-700 font-medium"
                >
                  <XCircle size={16} className="mr-1.5" /> Clear all filters
                </button>
              )}

            </div>
          </aside>

          {/* Main Grid */}
          <div className="flex-1">
            {filteredCourses.length > 0 ? (
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                {filteredCourses.map(course => (
                  <CourseCard 
                    key={course.id} 
                    course={course} 
                    searchQuery={filters.search}
                    onClick={handleCourseClick} 
                  />
                ))}
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center py-20 text-slate-400">
                <Search size={48} className="mb-4 text-slate-200" />
                <h3 className="text-lg font-medium text-slate-600">No courses found</h3>
                <p>Try adjusting your filters or search terms.</p>
                <button 
                  onClick={resetFilters}
                  className="mt-4 text-indigo-600 font-semibold hover:underline"
                >
                  Clear all filters
                </button>
              </div>
            )}
          </div>
        </div>
      </main>

      {/* Scroll to Top Button */}
      {showScrollTop && (
        <button
          onClick={scrollToTop}
          className="fixed bottom-36 right-6 z-30 bg-white text-slate-500 p-3 rounded-full shadow-lg border border-slate-200 hover:bg-indigo-50 hover:text-indigo-600 transition-all duration-300 transform hover:scale-110"
          aria-label="Scroll to top"
        >
          <ArrowUp size={20} />
        </button>
      )}

      {/* Fixed Footer */}
      <footer className="fixed bottom-0 left-0 right-0 z-50 bg-white/95 backdrop-blur-sm border-t border-slate-200 py-2 shadow-[0_-1px_2px_rgba(0,0,0,0.03)] h-12 flex items-center">
        <div className="w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex items-center justify-between text-xs text-slate-500">
           <div className="flex items-center gap-2">
             <Layers size={14} className="text-indigo-600" />
             <span className="font-semibold text-slate-700">SkillZaty</span>
             <span>© 2025</span>
           </div>
           <p className="font-mono text-[10px] text-slate-400">v{APP_VERSION}</p>
        </div>
      </footer>

      <CourseModal 
        course={selectedCourse} 
        initialVideoIndex={initialVideoIndex}
        onClose={() => {
          setSelectedCourse(null);
          setInitialVideoIndex(null);
        }} 
      />
      
    </div>
  );
};

export default App;